### ISSUE TITLE
Broken on plasma 5.13/5.47 Qt 5.10

### ISSUE THREAD

**Issue by hjri** [trueleo/me.trueleo.cuteshapes#2]
My System:
![image](https://user-images.githubusercontent.com/3514245/42827396-ea1a624a-89ee-11e8-8be4-9a51518c5af2.png)

This line seems to break wallpaper completely because QML 5.11 is only available in `experimental` branch of Debian. With that line present I only get solid black background.
https://github.com/trueleo/me.trueleo.cuteshapes/blob/master/contents/ui/main.qml#L1

Removing that line (since KDE bundled live wallpapers don't seem to have it and it's not used anywhere in file) makes live wallpaper load but it looks like this for me:
![image](https://user-images.githubusercontent.com/3514245/42827380-e1ddd404-89ee-11e8-98ef-7477c1d4c717.png)

Checking "hide logo" makes logo go away but no circle appears, just background itself. Also background looks stretched on 16:10 aspect ratio.

**Comment by trueleo** [comment]
Wallpaper is svg so aspect ratio will be fixed easily. And for QtQml I will try to use a lower version that is available on all distros. Thanks for report.

**Comment by hjri** [comment]
I tried putting lower version there, like QtQml 5.10 which i seem to have installed but it still complained that it isn't.

**Comment by trueleo** [comment]
@hjri  QtQml 2.0 is supported on Qt 5.9/5.10 (LTS). QtQml is needed for timer to work. It isn't needed for any visual elements. Things you can try is editing top lines and use   
`import QtQml 2.0`
`import QtQuick 2.7`

**Comment by trueleo** [comment]
@hjri I've made some changes to wallpaper so that it can fit into various aspect ratio. Qt modules version are according to Qt 5.10

**Comment by hjri** [comment]
Commit d343cf7 work for me now, everything seems to be ok, thank you.
